apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/TimBogevich/airflow3-argocd.git
    targetRevision: HEAD
    path: airflow  # указывает на директорию с Chart.yaml
    helm:
      values: |
        fernetKey: 'dGVzdA=='
        defaultAirflowTag: "3.0.1"
        createUserJob:
          applyCustomEnv: false
          useHelmHooks: false
        migrateDatabaseJob:
          applyCustomEnv: false
          jobAnnotations:
            'argocd.argoproj.io/hook': Sync
          useHelmHooks: false
        useStandardNaming: true
        ingress:
          enabled: true
          web:
            annotations:
              kubernetes.io/ingress.class: nginx
            host: airflow.local
            tls: 
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true