createUserJob:
  applyCustomEnv: false
  useHelmHooks: false
migrateDatabaseJob:
  applyCustomEnv: false
  jobAnnotations:
    'argocd.argoproj.io/hook': Sync
  useHelmHooks: false
useStandardNaming: true