createUserJob:
  applyCustomEnv: false
  useHelmHooks: false

migrateDatabaseJob:
  applyCustomEnv: false
  jobAnnotations:
    'argocd.argoproj.io/hook': Sync
  useHelmHooks: false

useStandardNaming: true

ingress:
  enabled: true
  web:
    annotations:
      kubernetes.io/ingress.class: nginx
    host: airflow.local
    tls:
      enabled: false
